#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2',         '0.99.4'
cookbook 'apt',             '1.1.2'
cookbook 'build-essential', '1.0.0'
cookbook 'gpg',             '0.0.1'
cookbook 'java',            '1.1.0'
cookbook 'jenkins',
  :git => 'git@github.com:patcon/chef-jenkins.git',
  :ref =>                   '0.6.0'
cookbook 'leiningen',       '0.2.0'
cookbook 'pennyworth',
  :git => 'git@github.com:patcon/chef-pennyworth.git',
  :ref =>                   '0.2.1'
cookbook 'postfix',         '0.8.4'
cookbook 'reprepro',
  :git => 'git@github.com:patcon/chef-reprepro.git',
  :ref =>                   '0.3.0'
cookbook 'runit',           '0.14.2'
